using System.Reflection;

namespace ArchitectureTests;

/// <summary>
/// A fifteen year old codebase does not pass a boundary rule you write today, and a rule
/// that fails on day one gets disabled on day two. So every rule here is measured against a
/// recorded baseline: the types that already violate it, listed by name, frozen.
///
/// New violations fail the build. Baseline entries that stop violating the rule also fail
/// the build, which is what keeps the list from becoming a parking lot: it can only shrink.
/// </summary>
public static class Baseline
{
    public static bool Writing => Environment.GetEnvironmentVariable("ARCH_BASELINE_WRITE") == "1";

    private static string Directory =>
        Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!, "baseline");

    private static string SourceDirectory
    {
        get
        {
            // walk up from bin/Debug/net9.0 to the project folder so a rewrite lands in git
            var dir = new DirectoryInfo(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);
            while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "ArchitectureTests.csproj")))
                dir = dir.Parent;
            return Path.Combine(dir?.FullName ?? Directory, "baseline");
        }
    }

    public static IReadOnlyCollection<string> Load(string ruleId)
    {
        var path = Path.Combine(Directory, ruleId + ".txt");
        if (!File.Exists(path))
            return Array.Empty<string>();

        return File.ReadAllLines(path)
            .Select(line => line.Trim())
            .Where(line => line.Length > 0 && !line.StartsWith('#'))
            .ToHashSet(StringComparer.Ordinal);
    }

    public static void Write(string ruleId, string headline, IEnumerable<string> failingTypes)
    {
        System.IO.Directory.CreateDirectory(SourceDirectory);
        var lines = new List<string>
        {
            "# " + ruleId,
            "# " + headline,
            "# Types that already break this rule in the pinned upstream commit. Generated by",
            "# scripts/update_baseline.sh. New names may not be added by hand: a change that",
            "# needs a new line here is a change that needs a conversation.",
        };
        lines.AddRange(failingTypes.OrderBy(name => name, StringComparer.Ordinal));
        File.WriteAllLines(Path.Combine(SourceDirectory, ruleId + ".txt"), lines);
    }
}
